name: Tauri Build

on:
  push:
    branches:
      - github-workspaces-test
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Tauri App
    runs-on: ubuntu-latest
    steps:
      - name: Actions 
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1

      - name: Install Dependencies for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev \
            libayatana-appindicator3-dev \
            libsoup2.4-dev \
            libglib2.0-dev \
            libwebkit2gtk-4.0-dev \
            libnotify-dev

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm@9.7.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build 

      - name: Run tests
        run: cargo test --verbose

