name: Tauri Build

on:
  push:
    branches:
      - github-workspaces-test
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    name: Rust And Cargo Setup
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1

  build:
    name: Build Tauri App
    runs-on: ubuntu-latest
    needs: setup 
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build 

      - name: Run tests
        run: cargo test --verbose

